# Generated by Django 5.0.3 on 2024-03-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
