# Generated by Django 5.0.3 on 2024-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Desc',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
